package(
    default_visibility = [
        "//tensorflow_serving:internal",
    ]
)

cc_library(
    name = 'custom_ops',
    srcs = [
        "//tensorflow_serving/custom_ops/tensorflow_text:tensorflow_text_ops"
    ],
    alwayslink = 1
)
