# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM tensorflow/serving:1.9.0

# Install dependencies
RUN apt-get update && apt-get install -y \
        curl \
        libcurl3-dev \
        zip \
        unzip \
        jq \
        gcc \
        software-properties-common \
        python-dev \
        python-pip \
        && apt-get clean \
        && apt-get autoremove \
        && add-apt-repository ppa:ubuntu-toolchain-r/test -y \
        && apt-get update \
        && apt-get install -y libstdc++6 \
        && pip install awscli

# Add scripts, in future liveness and readiness scripts too
COPY scripts scripts
# Set where models should be stored in the container
ENV MODEL_BASE_PATH=/models 
# The only required piece is the model name in order to differentiate endpoints
ENV MODEL_NAME=model
# if not set, will not sync with s3; e.g.: "s3://mybucket"
ENV S3_BUCKET="" 

RUN mkdir -p ${MODEL_BASE_PATH} \
    && chmod +x /usr/bin/tensorflow_model_server scripts/entrypoint.sh \
    && ls -la /usr/bin/tensorflow_model_server

EXPOSE 8500
EXPOSE 8501
ENTRYPOINT scripts/entrypoint.sh