# Description: net_http/internal/testing

package(
    default_applicable_licenses = ["//tensorflow_serving:license"],
    default_visibility = ["//visibility:private"],
)

licenses(["notice"])

cc_binary(
    name = "net_logging_example",
    srcs = ["net_logging_example.cc"],
    deps = [
        "//tensorflow_serving/util/net_http/internal:net_logging",
    ],
)
