# Description: Tensorflow Serving batching test data.

package(
    default_visibility = ["//tensorflow_serving:internal"],
    features = ["-layering_check"],
)

licenses(["notice"])

filegroup(
    name = "matrix_half_plus_two",
    srcs = glob(
        ["matrix_half_plus_two/**/*"],
    ),
)
