
licenses(["notice"])  # Apache 2.0

cc_library(name="tfclient",
           srcs=["tf_client.cc","prediction_service.grpc.pb.cc","prediction_service.pb.cc","predict.grpc.pb.cc","resource_handle.pb.cc",\
"tensor.pb.cc","predict.pb.cc","tfmodel.pb.cc","tensor_shape.pb.cc","types.pb.cc","libprotobuf.a","libgrpc.a"],
           hdrs=["tf_client.h","tfmodel.pb.h","predict.pb.h","prediction_service.pb.h","tensor.pb.h",\
"types.pb.h","predict.grpc.pb.h","prediction_service.grpc.pb.h","resource_handle.pb.h","tensor_shape.pb.h"],
          )
