// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: predict.proto
#ifndef GRPC_predict_2eproto__INCLUDED
#define GRPC_predict_2eproto__INCLUDED

#include "predict.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tensorflow {
namespace serving {

}  // namespace serving
}  // namespace tensorflow


#endif  // GRPC_predict_2eproto__INCLUDED
