# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/apis/syntaxnet_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from syntaxnet import sentence_pb2 as syntaxnet_dot_sentence__pb2
from tensorflow_serving.apis import model_pb2 as tensorflow__serving_dot_apis_dot_model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_serving/apis/syntaxnet_service.proto',
  package='tensorflow.serving',
  syntax='proto3',
  serialized_pb=_b('\n/tensorflow_serving/apis/syntaxnet_service.proto\x12\x12tensorflow.serving\x1a\x18syntaxnet/sentence.proto\x1a#tensorflow_serving/apis/model.proto\"j\n\x10SyntaxNetRequest\x12\x31\n\nmodel_spec\x18\x01 \x01(\x0b\x32\x1d.tensorflow.serving.ModelSpec\x12#\n\x06inputs\x18\x02 \x03(\x0b\x32\x13.syntaxnet.Sentence\"9\n\x11SyntaxNetResponse\x12$\n\x07outputs\x18\x01 \x03(\x0b\x32\x13.syntaxnet.Sentence2h\n\x10SyntaxNetService\x12T\n\x05Parse\x12$.tensorflow.serving.SyntaxNetRequest\x1a%.tensorflow.serving.SyntaxNetResponseb\x06proto3')
  ,
  dependencies=[syntaxnet_dot_sentence__pb2.DESCRIPTOR,tensorflow__serving_dot_apis_dot_model__pb2.DESCRIPTOR,])




_SYNTAXNETREQUEST = _descriptor.Descriptor(
  name='SyntaxNetRequest',
  full_name='tensorflow.serving.SyntaxNetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_spec', full_name='tensorflow.serving.SyntaxNetRequest.model_spec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='tensorflow.serving.SyntaxNetRequest.inputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=240,
)


_SYNTAXNETRESPONSE = _descriptor.Descriptor(
  name='SyntaxNetResponse',
  full_name='tensorflow.serving.SyntaxNetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputs', full_name='tensorflow.serving.SyntaxNetResponse.outputs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=299,
)

_SYNTAXNETREQUEST.fields_by_name['model_spec'].message_type = tensorflow__serving_dot_apis_dot_model__pb2._MODELSPEC
_SYNTAXNETREQUEST.fields_by_name['inputs'].message_type = syntaxnet_dot_sentence__pb2._SENTENCE
_SYNTAXNETRESPONSE.fields_by_name['outputs'].message_type = syntaxnet_dot_sentence__pb2._SENTENCE
DESCRIPTOR.message_types_by_name['SyntaxNetRequest'] = _SYNTAXNETREQUEST
DESCRIPTOR.message_types_by_name['SyntaxNetResponse'] = _SYNTAXNETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SyntaxNetRequest = _reflection.GeneratedProtocolMessageType('SyntaxNetRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYNTAXNETREQUEST,
  __module__ = 'tensorflow_serving.apis.syntaxnet_service_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.SyntaxNetRequest)
  ))
_sym_db.RegisterMessage(SyntaxNetRequest)

SyntaxNetResponse = _reflection.GeneratedProtocolMessageType('SyntaxNetResponse', (_message.Message,), dict(
  DESCRIPTOR = _SYNTAXNETRESPONSE,
  __module__ = 'tensorflow_serving.apis.syntaxnet_service_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.SyntaxNetResponse)
  ))
_sym_db.RegisterMessage(SyntaxNetResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class SyntaxNetServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Parse = channel.unary_unary(
          '/tensorflow.serving.SyntaxNetService/Parse',
          request_serializer=SyntaxNetRequest.SerializeToString,
          response_deserializer=SyntaxNetResponse.FromString,
          )


  class SyntaxNetServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Parse(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SyntaxNetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Parse': grpc.unary_unary_rpc_method_handler(
            servicer.Parse,
            request_deserializer=SyntaxNetRequest.FromString,
            response_serializer=SyntaxNetResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'tensorflow.serving.SyntaxNetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSyntaxNetServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Parse(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSyntaxNetServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Parse(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Parse.future = None


  def beta_create_SyntaxNetService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('tensorflow.serving.SyntaxNetService', 'Parse'): SyntaxNetRequest.FromString,
    }
    response_serializers = {
      ('tensorflow.serving.SyntaxNetService', 'Parse'): SyntaxNetResponse.SerializeToString,
    }
    method_implementations = {
      ('tensorflow.serving.SyntaxNetService', 'Parse'): face_utilities.unary_unary_inline(servicer.Parse),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_SyntaxNetService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('tensorflow.serving.SyntaxNetService', 'Parse'): SyntaxNetRequest.SerializeToString,
    }
    response_deserializers = {
      ('tensorflow.serving.SyntaxNetService', 'Parse'): SyntaxNetResponse.FromString,
    }
    cardinalities = {
      'Parse': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'tensorflow.serving.SyntaxNetService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
