name: 'CSAT survey'
on:
  issues:
    types:
      - closed

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./\.github/workflows/scripts/CSAT.js')
            script({github, context})